### ISSUE TITLE
No text near zoom and playback speed

### ISSUE THREAD

**Issue by NSaranov** [rualark/MGen#2036]
![image](https://user-images.githubusercontent.com/15021764/37257449-9ee3774a-257a-11e8-84b8-fbf4e3596b07.png)

**Comment by rualark** [comment]
This happens only at low resolution

**Comment by rualark** [comment]
Also, this happens if window width is reduced by dragging

**Comment by rualark** [comment]
Also, prompts for spin controls are not showing (showing only when mouseover caption).

**Comment by rualark** [comment]
Seems to be buggy mfc ribbon behavior
