### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by nunojesus** [rualark/MGen#2170]
Hi,
I have read your work so I decided to creat a logo for you. I hope you like it and you want to use it. I can give you all the formats of the design free. If you want to make changes please specify.

I used the colours of your website.

Greetings

![algo](https://user-images.githubusercontent.com/34600369/39490606-4ddcbbde-4d81-11e8-9972-2315d0e0950a.png)

**Comment by rualark** [comment]
Hi. Thank you for your effort! This was a bit unexpected. I currently use this logo:
![image](https://user-images.githubusercontent.com/15198808/39513262-77b7df94-4dfc-11e8-8075-336e3bd35eaf.png)

**Comment by nunojesus** [comment]
Ok no problem!

Good luck for your project!
